### ISSUE TITLE
Integrate go dep for dependency management

### ISSUE THREAD

**Issue by zhikiri** [zhikiri/gobls3#5]
Currently I'm using `go get`, but want to implement `go dep`.
Need to initialize and add all dependencies in to project

**Comment by marcosinger** [comment]
hey @zhikiri, did you mean use [dep](https://github.com/golang/dep) as dependency tool?

If so I can help with this :)

**Comment by zhikiri** [comment]
Hi @marcosinger. Yeah, currently we using standard, built it, 'go get' solution. And it's not really straightforward. 

So we need to switch to go dep, and store sources with vendor in repo. 

Also, dockerfile should be modified. But if you are not familiar with this, it's okay, just skip it.

Thanks!

**Comment by marcosinger** [comment]
It's done @zhikiri .. let me know what do you think :)
